/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `username` TEXT NOT NULL,
  `passwordHash` TEXT NOT NULL,
  `salt` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `salt_i`
  ON `User` (`salt`);
