name: Ubuntu CI Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo add-apt-repository ppa:pistache+team/unstable && sudo apt update && sudo apt install -y libpistache-dev odb gcovr lcov libsqlite3-dev libargon2-dev
    - name: prepare
      run: |
        make prepare
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
    - name: building
      run: |
        cmake --build build --config Debug
